export { default as About } from './about/About'
export { default as Cards } from './cards/Cards'
export { default as Download } from './download/Download'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Navbar } from './navbar/Navbar'
export { default as Review } from './review/Review'